POST http://localhost:5000/api/user
Content-Type: application/json

{
    "firstName": "User2",
    "lastName": "LastName2",
    "email": "User2@gmail.com",
    "password": "1234",
    "addressLine1": "12th street",
    "addressLine2": "baker road",
    "locationId": "f3c392ca-4e26-48f2-844d-8a5beb24d086",
    "phoneNumber": 9409809199
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "anurag@gmail.com",
    "password": "1234"
}

### setting the user as host
PUT http://localhost:5000/api/user/host/e24e95c6-31f9-4da3-8448-bbd040a06b93
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5ODQwMDY0LCJleHAiOjE2Mzk4NDEyNjR9.TX8J6VSKU719fvx4RLipkyACIAbXCvda1D7hpECeq34
###
GET http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5ODM0MDc4LCJleHAiOjE2Mzk4MzUyNzh9.PfmqoeOg8g8917mHRyTlm_1pzhchHR1CS08rpVUSyXg
###
GET http://localhost:5000/api/auth/refreshToken

###
DELETE http://localhost:5000/api/auth/refreshToken

###
GET http://localhost:5000/api/booking/rental/cost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5ODM0MDc4LCJleHAiOjE2Mzk4MzUyNzh9.PfmqoeOg8g8917mHRyTlm_1pzhchHR1CS08rpVUSyXg

### Adding a new rental
POST http://localhost:5000/api/rental
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5ODM0MjQ3LCJleHAiOjE2Mzk4MzU0NDd9.AfHcO96xdhOPi6MPgePfV843e4vuhYUxkYFBlVeBd9Y
Content-Type: application/json

{
    "name": "mansion3",
    "description": "This is a rich people mansion",
    "addressLine1": "78th Random address",
    "addressLine2": "No-where Lane",
    "location_id": "b68f029b-4f95-4f0a-b15c-afb737c88643",
    "dateFrom": "2021-12-20",
    "dateTo": "2021-12-25",
    "pricePerDay": 1500,
    "rentalTypeId": "c1a7c5f4-d9d0-412d-9ca1-86390d409988",
    "numberOfRooms": 2,
    "numberOfGuests": 4,
    "services": ["c8d912d0-eaed-4072-8d46-daa27ad1aab3", "f18c5974-ea89-4d3d-871e-47099ef1bfca"],
    "host_id": "e24e95c6-31f9-4da3-8448-bbd040a06b93"
}


### GETTING rental details by ID 
GET http://localhost:5000/api/rental/b6a2b99f-2dbb-4f9e-ba67-0228c8d50ad7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5ODMzMzY0LCJleHAiOjE2Mzk4MzQ1NjR9.qFUNk5hjMSb7RMo-Gb1mX4_bO0_IiUFtn1MKF2oSlrE


### POSTing a new booking
POST http://localhost:5000/api/booking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5OTExNjU5LCJleHAiOjE2Mzk5MTQ2NTl9.bcJXj-cPm5NzGiapVoT9QZxyUfOOKwq5i9caNsW_HCk
Content-Type: application/json

{
    "rentalId": "b6a2b99f-2dbb-4f9e-ba67-0228c8d50ad7",
    "userId": "677f1bbb-a5b5-4b27-8c6f-368725abdbb8",
    "bookFrom": "2020-11-25",
    "bookTo": "2020-12-01",
    "amount": 540, 
    "numberOfGuests": 2
    
}

###
GET http://localhost:5000/api/booking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5OTE3NzM4LCJleHAiOjE2Mzk5MjA3Mzh9.2YAMd3muTHQkgFerMpFIs19PIhqensUbquFu8ASAnVY

### CHECK if booking is available
GET http://localhost:5000/api/booking/availability
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5OTE3NzM4LCJleHAiOjE2Mzk5MjA3Mzh9.2YAMd3muTHQkgFerMpFIs19PIhqensUbquFu8ASAnVY
Content-Type: application/json

{
    "rentalId": "b6a2b99f-2dbb-4f9e-ba67-0228c8d50ad7",
    "bookFrom": "2021-11-25",
    "bookTo": "2021-12-01"  
}


### Calculate final Cost
GET http://localhost:5000/api/booking/rental/cost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5OTE3NzM4LCJleHAiOjE2Mzk5MjA3Mzh9.2YAMd3muTHQkgFerMpFIs19PIhqensUbquFu8ASAnVY
Content-Type: application/json

{
    "rentalId": "b6a2b99f-2dbb-4f9e-ba67-0228c8d50ad7",
    "bookFrom": "2021-11-25",
    "bookTo": "2021-12-01"  
}

### GET all services
GET http://localhost:5000/api/rental/info/service
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5ODUxNjg2LCJleHAiOjE2Mzk4NTI4ODZ9.cQcFnJYE43NxD_zEd5fxdz0wifLm_VuBzlIqNewjkv4


###GET all rental types
GET http://localhost:5000/api/rental/info/rentalType
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5OTA3NTExLCJleHAiOjE2Mzk5MTA1MTF9.o_huaxWmi8H8IOTchFiGiOOYHobDUxGsM1Fkus9xsPQ


### GET most booked Rentals
GET http://localhost:5000/api/home/mostBooked
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5OTE3NzM4LCJleHAiOjE2Mzk5MjA3Mzh9.2YAMd3muTHQkgFerMpFIs19PIhqensUbquFu8ASAnVY

### Add a review
POST http://localhost:5000/api/rental/b6a2b99f-2dbb-4f9e-ba67-0228c8d50ad7/review
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTA5NDEyLCJleHAiOjE2NDAxMTI0MTJ9.mmC6BXNVHz4NalwUUpxRMVtcFe74WPFTMAHxOfYQD6k
Content-Type: application/json

{
    "traveler_id": "677f1bbb-a5b5-4b27-8c6f-368725abdbb8",
    "description": "Good",
    "stars": 3
}

### Get all locations
GET http://localhost:5000/api/home/location
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTA5NDEyLCJleHAiOjE2NDAxMTI0MTJ9.mmC6BXNVHz4NalwUUpxRMVtcFe74WPFTMAHxOfYQD6k

### Get most recent rentals
GET http://localhost:5000/api/home/mostRecent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTEzMzQ2LCJleHAiOjE2NDAxMTYzNDZ9.jqRMA-6Ue3DkameaXnAA7cA6CjNjryQ8thO0hAWSGB0