POST http://localhost:5000/api/user
Content-Type: application/json

{
    "firstName": "User1",
    "lastName": "Kakkan",
    "email": "anurag1@gmail.com",
    "password": "1234",
    "addressLine1": "12th street",
    "addressLine2": "baker road",
    "locationId": "b16eecbb-f714-447a-b91e-7647bab3a7e2",
    "phoneNumber": 9409809198
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "anurag@gmail.com",
    "password": "1234"
}

### setting the user as host
PUT http://localhost:5000/api/user/host/e24e95c6-31f9-4da3-8448-bbd040a06b93
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5ODQwMDY0LCJleHAiOjE2Mzk4NDEyNjR9.TX8J6VSKU719fvx4RLipkyACIAbXCvda1D7hpECeq34

###
GET http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5ODM0MDc4LCJleHAiOjE2Mzk4MzUyNzh9.PfmqoeOg8g8917mHRyTlm_1pzhchHR1CS08rpVUSyXg
###
GET http://localhost:5000/api/auth/refreshToken

###
DELETE http://localhost:5000/api/auth/refreshToken

###
GET http://localhost:5000/api/booking/rental/cost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5ODM0MDc4LCJleHAiOjE2Mzk4MzUyNzh9.PfmqoeOg8g8917mHRyTlm_1pzhchHR1CS08rpVUSyXg

### Adding a new rental
POST http://localhost:5000/api/rental
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTUyMGUzZTUtZTc1ZS00MDIzLWE1MzEtMjNjMDJmOGJiNzgwIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTk0MzYyLCJleHAiOjE2NDAxOTczNjJ9._Lc_gKMMpe_A7MGkkujhz6n-avQyI-QH0Z1YQAlGn_Y
Content-Type: application/json

{
    "name": "Service Tester",
    "description": "This is a rich people mansion",
    "addressLine1": "78th Random address",
    "addressLine2": "No-where Lane",
    "location_id": "2471448f-f88e-4997-8c41-009a6ebd6fd8",
    "dateFrom": "2022-01-10",
    "dateTo": "2022-01-15",
    "pricePerDay": 1500,
    "rentalTypeId": "90bd81b4-647d-4cec-afb9-c7a33044e943",
    "numberOfRooms": 2,
    "numberOfGuests": 4,
    "services": ["bd45cb80-06bf-42ad-ac41-d5690c6b2666", "e0538aec-5287-48ff-858e-ed1f5dbd0038", "418fe8cc-5d1d-41df-8e8b-692c17c8b8ae", "891f5f7d-2c48-4777-89e9-06f77e12db46", "4bc59315-c62e-4986-b3e9-e8ce1178050b", "165d2b68-5d8d-44fd-a549-e7349fc70aaa"],
    "host_id": "88956e70-7daa-4ca7-977f-91a1357f8cee",
    "numberOfBeds": 2
}


### GETTING All Rentals
GET http://localhost:5000/api/rental/info/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTUyMGUzZTUtZTc1ZS00MDIzLWE1MzEtMjNjMDJmOGJiNzgwIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTY2MjIyLCJleHAiOjE2NDAxNjkyMjJ9.dc1BKzfgxXHoaU3EQylTjNRL1YWabUS6ZKVfjyzxhpI


### GETTING rental details by ID 
GET http://localhost:5000/api/rental/info/a520e3e5-e75e-4023-a531-23c02f8bb780
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTUyMGUzZTUtZTc1ZS00MDIzLWE1MzEtMjNjMDJmOGJiNzgwIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTc4NDAyLCJleHAiOjE2NDAxODE0MDJ9.Qm5vPnNvjcAqz6nIdFnuyFJo-EjUjMkELD0bumIZJgI



### GETTING bookings by user ID 
GET http://localhost:5000/api/booking/a520e3e5-e75e-4023-a531-23c02f8bb780
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTUyMGUzZTUtZTc1ZS00MDIzLWE1MzEtMjNjMDJmOGJiNzgwIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTc4NDAyLCJleHAiOjE2NDAxODE0MDJ9.Qm5vPnNvjcAqz6nIdFnuyFJo-EjUjMkELD0bumIZJgI


### POSTing a new booking
POST http://localhost:5000/api/booking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTUyMGUzZTUtZTc1ZS00MDIzLWE1MzEtMjNjMDJmOGJiNzgwIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTc4NDAyLCJleHAiOjE2NDAxODE0MDJ9.Qm5vPnNvjcAqz6nIdFnuyFJo-EjUjMkELD0bumIZJgI
Content-Type: application/json

{
    "rentalId": "af0c33d7-8583-4142-88d4-83cc6493b262",
    "userId": "a520e3e5-e75e-4023-a531-23c02f8bb780",
    "bookFrom": "2020-11-25",
    "bookTo": "2020-12-01",
    "amount": 540, 
    "numberOfGuests": 2
    
}

###
GET http://localhost:5000/api/booking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5OTE3NzM4LCJleHAiOjE2Mzk5MjA3Mzh9.2YAMd3muTHQkgFerMpFIs19PIhqensUbquFu8ASAnVY

### CHECK if booking is available
GET http://localhost:5000/api/booking/availability
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTUyMGUzZTUtZTc1ZS00MDIzLWE1MzEtMjNjMDJmOGJiNzgwIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTcwNjk3LCJleHAiOjE2NDAxNzM2OTd9.-EUoR5g-8di3EKLBiTXsYqgj2m2T76CMQBGCCOEMr3s
Content-Type: application/json

{
    "rentalId": "e58832b1-163d-4a96-9f5e-d00f4714b76b",
    "bookFrom": "2021-11-25",
    "bookTo": "2021-12-01"  
}


### Calculate final Cost
GET http://localhost:5000/api/booking/rental/cost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTUyMGUzZTUtZTc1ZS00MDIzLWE1MzEtMjNjMDJmOGJiNzgwIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTcwNjk3LCJleHAiOjE2NDAxNzM2OTd9.-EUoR5g-8di3EKLBiTXsYqgj2m2T76CMQBGCCOEMr3s
Content-Type: application/json

{
    "rentalId": "e58832b1-163d-4a96-9f5e-d00f4714b76b",
    "bookFrom": "2021-11-25",
    "bookTo": "2021-12-25"
}

### GET all services
GET http://localhost:5000/api/rental/info/service
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5ODUxNjg2LCJleHAiOjE2Mzk4NTI4ODZ9.cQcFnJYE43NxD_zEd5fxdz0wifLm_VuBzlIqNewjkv4


###GET all rental types
GET http://localhost:5000/api/rental/info/rentalType
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5OTA3NTExLCJleHAiOjE2Mzk5MTA1MTF9.o_huaxWmi8H8IOTchFiGiOOYHobDUxGsM1Fkus9xsPQ


### GET most booked Rentals
GET http://localhost:5000/api/home/mostBooked
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjM5OTE3NzM4LCJleHAiOjE2Mzk5MjA3Mzh9.2YAMd3muTHQkgFerMpFIs19PIhqensUbquFu8ASAnVY

### Add a review
POST http://localhost:5000/api/rental/749787e5-122b-4af8-a4c5-770109fbc0d7/review
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTEzMzQ2LCJleHAiOjE2NDAxMTYzNDZ9.jqRMA-6Ue3DkameaXnAA7cA6CjNjryQ8thO0hAWSGB0
Content-Type: application/json

{
    "traveler_id": "0264e144-2862-4b4d-a9fd-c89c5a2d67dc",
    "description": "Good",
    "stars": 1
}

### Get all locations
GET http://localhost:5000/api/home/location
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTA5NDEyLCJleHAiOjE2NDAxMTI0MTJ9.mmC6BXNVHz4NalwUUpxRMVtcFe74WPFTMAHxOfYQD6k

### Get most recent rentals
GET http://localhost:5000/api/home/mostRecent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTUyMGUzZTUtZTc1ZS00MDIzLWE1MzEtMjNjMDJmOGJiNzgwIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTU5OTE5LCJleHAiOjE2NDAxNjI5MTl9.RPEZVxF_T0vdqXnPcvEQ6h7OOyHH83_0ZCUBZ1DGW6c

### Get average stars/reviews
GET http://localhost:5000/api/rental/b6a2b99f-2dbb-4f9e-ba67-0228c8d50ad7/avgReview
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTI0ZTk1YzYtMzFmOS00ZGEzLTg0NDgtYmJkMDQwYTA2YjkzIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTEzMzQ2LCJleHAiOjE2NDAxMTYzNDZ9.jqRMA-6Ue3DkameaXnAA7cA6CjNjryQ8thO0hAWSGB0

### GET rentals and bookings
GET http://localhost:5000/api/rental/info/booking/rentals/88956e70-7daa-4ca7-977f-91a1357f8cee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTUyMGUzZTUtZTc1ZS00MDIzLWE1MzEtMjNjMDJmOGJiNzgwIiwiZmlyc3RuYW1lIjoiQW51cmFnIiwiZW1haWwiOiJhbnVyYWdAZ21haWwuY29tIiwiaWF0IjoxNjQwMTk0MzYyLCJleHAiOjE2NDAxOTczNjJ9._Lc_gKMMpe_A7MGkkujhz6n-avQyI-QH0Z1YQAlGn_Y
